### ISSUE TITLE
部署好后无法访问页面，报错500

### ISSUE THREAD

**Issue by sky22333** [hiouttime/dujiaoka#8]
## 复现过程

```
docker build -t dujiaoka .
```

`docker-compose.yaml`

```
version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - /data/mysql/config/my.cnf:/etc/mysql/my.cnf
      - /data/mysql/db:/var/lib/mysql

  myredis:
    image: redis
    container_name: myredis
    ports:
      - "6379:6379"
    command: redis-server --requirepass "123456"

  dujiaoka:
    image: dujiaoka
    container_name: dujiaoka
    ports:
      - "8888:80"
      - "9000:9000"
    environment:
      - APP_URL=https://xxxxx.com
      - ADMIN_HTTPS=true
      - ADMIN_ROUTE_PREFIX=/admin
      - WEB_DOCUMENT_ROOT=/app/public
    restart: always
```

### 部署好后容器都运行正常，访问页面的时候容器内日志报错为：

```
dujiaoka | 2024/06/19 03:22:13 [错误] 66#66：*14 FastCGI 在 stderr 中发送：“PHP 消息：PHP 解析错误：语法错误，意外的‘|’，预期变量（T_VARIABLE）在 /app/vendor/nunomaduro/termwind/src/Functions.php 的第 17 行”，同时从上游读取响应头，客户端：xx.x.xxx.xx，服务器：_，请求：“GET / HTTP/1.1”，上游：“fastcgi://127.0.0.1:9000”，主机：“https://xxxxx.com”
dujiaoka |通知：PHP 消息：PHP 解析错误：语法错误，意外的“|”，预期变量（T_VARIABLE）位于 /app/vendor/nunomaduro/termwind/src/Functions.php 第 17 行
dujiaoka | [php-fpm:access] 127.0.0.1 - 19/Jun/2024:03:22:13 +0000 "GET /index.php" 500 /app/public/index.php 1.887 2048 0.00%
```

更换php版本也不行
